
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: payment_gateway_development


test:
  <<: *default
  database: test_payment_gateway

#production: # This is the production database configuration for the payment gateway uncomment this when deploying to production
#  <<: *default
#  database: <%#= ENV[:database_name] %>
#  username: <%#= ENV[:username] %>
#  password: <%#= ENV[:password] %>
#  host:     <%#= ENV[:host] %>
#  port:     <%#= ENV[:port] %>
